site_name: Roxbot Docs

theme:
  name: material
  palette:
    primary: green

plugins:
  - blog
  - search

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Blog:
      - blog/index.md
