site_name: Roxbot blog

theme:
  name: material
  palette:
    primary: green

plugins:
  - blog:
      blog_dir: .
  - search

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
