name: Build and Push docker images

on:
  push:
    branches:
      - main
    paths:
      - "docker/**"
      - ".github/workflows/build-images.yml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: mkdocs
      USERNAME: ${{ github.repository_owner }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev image
        run: |
          cd docker/dev
          docker build . -t ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:latest
