name: Test and release

on:
  push:
    branches:
      - main
    tags:
      - '*'  # For publishing to PyPI when a new tag is pushed
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install .

      - name: Run linting and type checks
        run: |
          pip install ruff mypy
          ruff check src tests
          mypy src

      - name: Run tests
        run: |
          pip install pytest
          pytest -v

  # Job to build and publish package to PyPI
  publish:
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: pip install build twine

      - name: Build the package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: python -m twine upload dist/*
